In [2]:
#To predict that will our customer buy again?


In [3]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

engine = create_engine( "mysql+pymysql://root:vedika123%40321@localhost:3306/ecommerce_analysis")
print(engine)

Engine(mysql+pymysql://root:***@localhost:3306/ecommerce_analysis)


In [4]:

#orders     → when did they order?
#payments   → how much did they spend?
#customers  → which actual customer made the order?

orders_df = pd.read_sql('''
select 
order_id,
customer_id,
order_purchase_timestamp
from orders;''',engine)


customers_df = pd.read_sql('''
select customer_id,
customer_unique_id
from customers;
''', engine)


payments_df = pd.read_sql('''
select order_id,
payment_value
from payments;
''', engine)

#To combine them now

orders_df = orders_df.merge(
    customers_df,
    on='customer_id'
,
how = 'inner')

payments_total = (
    payments_df.groupby('order_id')['payment_value']
    .sum()
    .reset_index()
)

orders_df = orders_df.merge(
    payments_total,
    on = 'order_id',
    how = 'left'
)


In [5]:
print(orders_df.head())
print(orders_df.shape)
print(orders_df.info())
print(orders_df.isnull().sum())

                           order_id  ... payment_value
0  e481f51cbdc54678b7cc49136f2d6af7  ...         38.71
1  53cdb2fc8bc7dce0b6741e2150273451  ...        141.46
2  47770eb9100c2d0c44946d9cf07ec65d  ...        179.12
3  949d5b44dbf5de918fe9c16f97b45f8a  ...         72.20
4  ad21c59c0840e6cb83a9ceb5573f8159  ...         28.62

[5 rows x 5 columns]
(99441, 5)
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   order_id                  99441 non-null  str    
 1   customer_id               99441 non-null  str    
 2   order_purchase_timestamp  99441 non-null  str    
 3   customer_unique_id        99441 non-null  str    
 4   payment_value             99440 non-null  float64
dtypes: float64(1), str(4)
memory usage: 14.7 MB
None
order_id                    0
customer_id                 0
order_purchase_timestamp    0
customer_un

In [6]:
orders_df[orders_df['payment_value'].isna()]

,order_id,customer_id,order_purchase_timestamp,customer_unique_id,payment_value
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15 12:16:38,830d5b7aaa3b6f1e9ad63703bec97d23,NaN


In [7]:
orders_df = orders_df.dropna(subset=['payment_value']).copy()
print(orders_df.isnull().sum())
print(orders_df.shape)

order_id                    0
customer_id                 0
order_purchase_timestamp    0
customer_unique_id          0
payment_value               0
dtype: int64
(99440, 5)


In [8]:
#To find wheteher each customer bought again

order_counts = orders_df['customer_unique_id'].value_counts()

print(order_counts.head())
print(order_counts.value_counts().sort_index())



customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
ca77025e7201e3b30c44b472ff346268     7
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
Name: count, dtype: int64
count
1     93098
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64


In [9]:
print('First Order : ', orders_df['order_purchase_timestamp'].min())
print('Last Order : ' , orders_df['order_purchase_timestamp'].max())



First Order :  2016-09-04 21:15:19
Last Order :  2018-10-17 17:30:18


In [10]:
#Orders before June 1 → used to understand the customer
#Orders on/after June 1 → used to determine whether they came back

orders_df['order_purchase_timestamp'] = pd.to_datetime(
    orders_df['order_purchase_timestamp']
)


#to separate past and future
cutoff_date = pd.Timestamp('2018-06-01')

past_data = orders_df[
    orders_df['order_purchase_timestamp'] < cutoff_date
].copy()


future_data = orders_df[
    orders_df['order_purchase_timestamp'] >= cutoff_date
].copy()


print('Past Data : ', past_data.shape)
print('Future Data : ' , future_data.shape)

Past Data :  (80449, 5)
Future Data :  (18991, 5)


In [11]:
future_customers = set(
    future_data['customer_unique_id']
) #list of customers who purchased after 1 june

past_data['Bought_Again'] = (
    past_data['customer_unique_id'].isin(future_customers).astype(int)
)

print(past_data['Bought_Again'].value_counts())

Bought_Again
0    79929
1      520
Name: count, dtype: int64


In [12]:
reference_date = cutoff_date

customer_features = (
    past_data
    .groupby('customer_unique_id')
    .agg(
        Recency = (
            'order_purchase_timestamp',
            lambda x: (reference_date - x.max()).days #How many days had passed since this customer's most recent order before the cutoff?
        ),
        Frequency = (
            'order_id',
            'nunique'#how many diff order did customer make
        ),
        Monetary = (
            'payment_value',
            'sum' #hgow much did the customer spend after cutoff
        )
    )
    .reset_index()
)

print(customer_features.head())
print(customer_features.shape)

                 customer_unique_id  Recency  Frequency  Monetary
0  0000366f3b9a7992bf8c76cfdf3221e2       21          1    141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f       24          1     27.19
2  0000f46a3911fa3c0805444483337064      447          1     86.22
3  0000f6ccb0745a6a4b88665a16c9f078      231          1     43.62
4  0004aac84e0df4da2b147fca70cf8255      198          1    196.89
(77807, 4)


In [13]:
target = (
    past_data[['customer_unique_id', 'Bought_Again']]
    .drop_duplicates('customer_unique_id')
)

customer_features = customer_features.merge(
    target,
    on = 'customer_unique_id',
    how='left'
)

print(customer_features.head())
print(customer_features.shape)
print(customer_features['Bought_Again'].value_counts())

                 customer_unique_id  Recency  Frequency  Monetary  Bought_Again
0  0000366f3b9a7992bf8c76cfdf3221e2       21          1    141.90             0
1  0000b849f77a49e4a4ce2b2a4ca5be3f       24          1     27.19             0
2  0000f46a3911fa3c0805444483337064      447          1     86.22             0
3  0000f6ccb0745a6a4b88665a16c9f078      231          1     43.62             0
4  0004aac84e0df4da2b147fca70cf8255      198          1    196.89             0
(77807, 5)
Bought_Again
0    77367
1      440
Name: count, dtype: int64


In [14]:
X = customer_features[[
    'Recency','Frequency','Monetary'
]]

y = customer_features['Bought_Again']

print(y.value_counts())
print()
print(y.value_counts(normalize=True)*100)

print("X:")
print(X.head())

print('\ny : ')
print(y.head())

Bought_Again
0    77367
1      440
Name: count, dtype: int64

Bought_Again
0    99.434498
1     0.565502
Name: proportion, dtype: float64
X:
   Recency  Frequency  Monetary
0       21          1    141.90
1       24          1     27.19
2      447          1     86.22
3      231          1     43.62
4      198          1    196.89

y : 
0    0
1    0
2    0
3    0
4    0
Name: Bought_Again, dtype: int64


In [15]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(
    X,
    y,
    random_state=42,
    stratify=y
)

print('Training Data : ' , X_train.shape)
print('Testing Data : ', X_test.shape)

Training Data :  (58355, 3)
Testing Data :  (19452, 3)


In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled[:5])

[[ 0.24280298 -0.16422889 -0.27006936]
 [-1.3433931   4.66376949  1.83443431]
 [ 0.95696709 -0.16422889 -0.48901968]
 [ 1.28022032 -0.16422889 -0.58217777]
 [-0.26838817 -0.16422889  0.12885653]]


In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter = 1000,
    class_weight='balanced', #dont tell our model class 0 is more balanced
    random_state=42
)

model.fit(X_train_scaled, y_train)
print('Model trained successfully')

Model trained successfully


In [18]:
y_pred = model.predict(X_test_scaled)
print(y_pred[:20])

[1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0]


In [19]:
from sklearn.metrics import classification_report,accuracy_score,precision_score,recall_score,confusion_matrix,f1_score

print('Accuracy : ' , accuracy_score(y_test , y_pred))
print('precision : ' , precision_score(y_test , y_pred))
print('Recall : ' , recall_score(y_test , y_pred))
print('F1 Score : ' , f1_score(y_test, y_pred))

print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Accuracy :  0.5849784083898828
precision :  0.007544836116264688
Recall :  0.5545454545454546
F1 Score :  0.014887126296522269
Confusion Matrix : 
[[11318  8024]
 [   49    61]]


In [20]:
print(y_train.value_counts())
print()
print(y_test.value_counts())

Bought_Again
0    58025
1      330
Name: count, dtype: int64

Bought_Again
0    19342
1      110
Name: count, dtype: int64


In [21]:
#Adding bette customer features

customer_features['Average_Order_Value'] = (
    customer_features['Monetary'] /
    customer_features['Frequency']
)

customer_features['Customer_Lifetime'] = (
    past_data.groupby('customer_unique_id')['order_purchase_timestamp']
    .agg(lambda x : (x.max() - x.min()).days).values
)

print(customer_features.head())

                 customer_unique_id  ...  Customer_Lifetime
0  0000366f3b9a7992bf8c76cfdf3221e2  ...                  0
1  0000b849f77a49e4a4ce2b2a4ca5be3f  ...                  0
2  0000f46a3911fa3c0805444483337064  ...                  0
3  0000f6ccb0745a6a4b88665a16c9f078  ...                  0
4  0004aac84e0df4da2b147fca70cf8255  ...                  0

[5 rows x 7 columns]


In [22]:
features = [
    'Recency',
    'Frequency',
    'Monetary',
    'Average_Order_Value',
    'Customer_Lifetime'
]

X = customer_features[features]
y = customer_features['Bought_Again']

print(X.head())
print(X.shape)

   Recency  Frequency  Monetary  Average_Order_Value  Customer_Lifetime
0       21          1    141.90               141.90                  0
1       24          1     27.19                27.19                  0
2      447          1     86.22                86.22                  0
3      231          1     43.62                43.62                  0
4      198          1    196.89               196.89                  0
(77807, 5)


In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (62245, 5)
Testing: (15562, 5)


In [24]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Model trained successfully!")

Model trained successfully!


In [26]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.580580902197661
Precision: 0.00764642911760208
Recall   : 0.5681818181818182
F1 Score : 0.01508978421608571

Confusion Matrix:
[[8985 6489]
 [  38   50]]


In [27]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators= 200,
    random_state= 42,
    class_weight='balanced',
    n_jobs=-1
)

rf_model.fit(X_train , y_train)
rf_pred = rf_model.predict(X_test)

print('Random forest trained succefully')

Random forest trained succefully


In [28]:
print("Accuracy :", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall   :", recall_score(y_test, rf_pred))
print("F1 Score :", f1_score(y_test, rf_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

Accuracy : 0.9908109497493895
Precision: 0.03389830508474576
Recall   : 0.022727272727272728
F1 Score : 0.027210884353741496

Confusion Matrix:
[[15417    57]
 [   86     2]]


In [29]:
rf_prob = rf_model.predict_proba(X_test)[:,1]
print(rf_prob[:20])

[0.09994737 0.         0.         0.         0.         0.
 0.         0.         0.         0.015      0.         0.035
 0.         0.         0.         0.         0.         0.
 0.         0.        ]


In [30]:
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)
print("rf_pred:", rf_pred.shape)

X_test: (15562, 5)
y_test: (15562,)
rf_pred: (15562,)


In [32]:
print('minimum probability : ' , rf_prob.min())
print('maximum probability : ' , rf_prob.max())

print('\n Probability Summary')
print(pd.Series(rf_prob).describe())

minimum probability :  0.0
maximum probability :  1.0

 Probability Summary
count    15562.000000
mean         0.013228
std          0.059780
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
dtype: float64


In [33]:
#How many positve customers sare presnt

print('Total Customers : ', len(y))

print('target Distribution : ')
print(y.value_counts())

print('\n target Percentage')
print(y.value_counts(normalize=True) * 100)

Total Customers :  77807
target Distribution : 
Bought_Again
0    77367
1      440
Name: count, dtype: int64

 target Percentage
Bought_Again
0    99.434498
1     0.565502
Name: proportion, dtype: float64


In [34]:
#Lets tune the logiustic regression properly

lr_prob = model.predict_proba(X_test_scaled)[:,1]
print(lr_prob[:20])

[0.55923325 0.44978724 0.46343291 0.12615033 0.47633335 0.53649193
 0.4364056  0.53752482 0.49689382 0.43970563 0.45799378 0.43081774
 0.27962275 0.4334917  0.12180407 0.50694883 0.4939921  0.49296932
 0.5581892  0.4032425 ]


In [36]:
thresholds = [0.5, 0.4, 0.3, 0.2, 0.1]

for threshold in thresholds:
    pred = (lr_prob >= threshold).astype(int)

    print(
        f"Threshold: {threshold} | "
        f"Precision: {precision_score(y_test, pred):.4f} | "
        f"Recall: {recall_score(y_test, pred):.4f} | "
        f"F1: {f1_score(y_test, pred):.4f}"
    )

Threshold: 0.5 | Precision: 0.0076 | Recall: 0.5682 | F1: 0.0151
Threshold: 0.4 | Precision: 0.0061 | Recall: 0.9318 | F1: 0.0122
Threshold: 0.3 | Precision: 0.0057 | Recall: 1.0000 | F1: 0.0114
Threshold: 0.2 | Precision: 0.0057 | Recall: 1.0000 | F1: 0.0113
Threshold: 0.1 | Precision: 0.0057 | Recall: 1.0000 | F1: 0.0113


In [37]:
#as all the thigs worked poorly

import pandas as pd
feature_importance = pd.DataFrame({
    'Feature' : X_train.columns,
    'Importance' : rf_model.feature_importances_
}).sort_values('Importance', ascending=False)

print(feature_importance)

               Feature  Importance
3  Average_Order_Value    0.322684
0              Recency    0.322669
2             Monetary    0.318580
4    Customer_Lifetime    0.024306
1            Frequency    0.011762


In [38]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators = 200,
    max_depth = 4,
    learning_rate = 0.05,
    random_state = 42,
    eval_metric = 'logloss'
)

xgb_model.fit(X_train , y_train)
xgb_pred = xgb_model.predict(X_test)
print('XGBoost trained successfully ! ')

XGBoost trained successfully ! 


In [39]:
print("Accuracy :", accuracy_score(y_test, xgb_pred))
print("Precision:", precision_score(y_test, xgb_pred))
print("Recall   :", recall_score(y_test, xgb_pred))
print("F1 Score :", f1_score(y_test, xgb_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_pred))

Accuracy : 0.9943451998457782
Precision: 0.0
Recall   : 0.0
F1 Score : 0.0

Confusion Matrix:
[[15474     0]
 [   88     0]]


c:\Users\VEDIKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [40]:
#To tell xgboost about class imbalance

scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print('Scale Pos Weight :', scale_pos_weight)

Scale Pos Weight : 175.83238636363637


In [41]:
xgb_model_balanced = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'
)

xgb_model_balanced.fit(X_train, y_train)

xgb_balanced_pred = xgb_model_balanced.predict(X_test)

print("Balanced XGBoost trained successfully!")

Balanced XGBoost trained successfully!


In [42]:
print("Accuracy :", accuracy_score(y_test, xgb_balanced_pred))
print("Precision:", precision_score(y_test, xgb_balanced_pred))
print("Recall   :", recall_score(y_test, xgb_balanced_pred))
print("F1 Score :", f1_score(y_test, xgb_balanced_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_balanced_pred))

Accuracy : 0.7669322709163346
Precision: 0.008062274117319988
Recall   : 0.32954545454545453
F1 Score : 0.015739484396200813

Confusion Matrix:
[[11906  3568]
 [   59    29]]


In [44]:
customer_features['Avg_Payment_Per_Order'] = (
    customer_features['Monetary'] /
    customer_features['Frequency']
)

customer_features['Total_Items'] = (
    past_data.groupby('customer_unique_id')['order_id'].count()
    .reindex(customer_features['customer_unique_id'])
.values
)



customer_features = customer_features.drop(
    columns=['Total_Items']


    
)

print(customer_features.head())

                 customer_unique_id  ...  Avg_Payment_Per_Order
0  0000366f3b9a7992bf8c76cfdf3221e2  ...                 141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f  ...                  27.19
2  0000f46a3911fa3c0805444483337064  ...                  86.22
3  0000f6ccb0745a6a4b88665a16c9f078  ...                  43.62
4  0004aac84e0df4da2b147fca70cf8255  ...                 196.89

[5 rows x 8 columns]


In [50]:
xgb_model_balanced = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'
)

xgb_model_balanced.fit(X_train, y_train)

xgb_balanced_pred = xgb_model_balanced.predict(X_test)

In [51]:
print("Accuracy :", accuracy_score(y_test, xgb_balanced_pred))
print("Precision:", precision_score(y_test, xgb_balanced_pred))
print("Recall   :", recall_score(y_test, xgb_balanced_pred))
print("F1 Score :", f1_score(y_test, xgb_balanced_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_balanced_pred))

Accuracy : 0.7669322709163346
Precision: 0.008062274117319988
Recall   : 0.32954545454545453
F1 Score : 0.015739484396200813

Confusion Matrix:
[[11906  3568]
 [   59    29]]
